from flask import Flask, jsonify, request # importing flask

app = Flask(__name__)

movies = [
    {
        'id': 1,
        'name': 'Mad Max: Fury Road',
        'synopsis': 'In a post-apocalyptic future, Max joins Furiosa on a mission to save a group of women from a tyrant.',
        'genres': ['Action', 'Sci-Fi'],
        'director': 'George Miller',
        'cast': ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
        'year': 2015,
        'country': 'Australia',
        'rating': 16,
    },
    {
        'id': 2,
        'name': 'Spider-Man: Homecoming',
        'synopsis': 'Peter Parker tries to balance his life as a high school student and a superhero while dealing with the villain Vulture.',
        'genres': ['Action', 'Adventure', 'Sci-Fi'],
        'director': 'Jon Watts',
        'cast': ['Tom Holland', 'Michael Keaton', 'Robert Downey Jr.'],
        'year': 2017,
        'country': 'USA',
        'rating': 12,
    },
    {
        'id': 3,
        'name': 'Avengers: Infinity War',
        'synopsis': 'The Avengers unite to face Thanos and try to prevent the destruction of the universe.',
        'genres': ['Action', 'Adventure', 'Sci-Fi'],
        'director': 'Anthony Russo, Joe Russo',
        'cast': ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
        'year': 2018,
        'country': 'USA',
        'rating': 12,
    },
    {
        'id': 4,
        'name': 'Jurassic World',
        'synopsis': 'A theme park with genetically modified dinosaurs falls into chaos when a new dangerous dinosaur is released.',
        'genres': ['Action', 'Adventure', 'Sci-Fi'],
        'director': 'Colin Trevorrow',
        'cast': ['Chris Pratt', 'Bryce Dallas Howard', 'Vincent D\'Onofrio'],
        'year': 2015,
        'country': 'USA',
        'rating': 12,
    },
    {
        'id': 5,
        'name': 'Guardians of the Galaxy',
        'synopsis': 'A group of misfit intergalactic beings unite to stop a mad villain from destroying the universe.',
        'genres': ['Action', 'Adventure', 'Comedy'],
        'director': 'James Gunn',
        'cast': ['Chris Pratt', 'Zoe Saldana', 'Dave Bautista'],
        'year': 2014,
        'country': 'USA',
        'rating': 12,
    },
    {
        'id': 6,
        'name': 'The Dark Knight',
        'synopsis': 'The Dark Knight returns to Gotham to face the Joker, a psychotic criminal who threatens to destroy the city.',
        'genres': ['Action', 'Crime', 'Drama'],
        'director': 'Christopher Nolan',
        'cast': ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
        'year': 2008,
        'country': 'USA',
        'rating': 16,
    },
    {
        'id': 7,
        'name': 'Star Wars: The Empire Strikes Back',
        'synopsis': 'The Rebellion faces the Empire, while Luke Skywalker tries to train as a Jedi and confronts Darth Vader.',
        'genres': ['Adventure', 'Sci-Fi'],
        'director': 'Irvin Kershner',
        'cast': ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
        'year': 1980,
        'country': 'USA',
        'rating': 12,
    },
    {
        'id': 8,
        'name': 'Psycho',
        'synopsis': 'A disturbed young man named Norman Bates manages the Bates Motel, where he becomes involved in the mystery surrounding Marion Crane’s disappearance.',
        'genres': ['Thriller', 'Horror'],
        'director': 'Alfred Hitchcock',
        'cast': ['Anthony Perkins', 'Janet Leigh', 'Vera Miles'],
        'year': 1960,
        'country': 'USA',
        'rating': 14,
    },
    {
        'id': 9,
        'name': 'Inception',
        'synopsis': 'A skilled thief who steals corporate secrets through dream-sharing technology is given a chance to have his criminal history erased if he can implant an idea into a target’s subconscious.',
        'genres': ['Action', 'Sci-Fi', 'Thriller'],
        'director': 'Christopher Nolan',
        'cast': ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
        'year': 2010,
        'country': 'USA',
        'rating': 12,
    },
    {  
        'id': 10,
        'name': 'Parasite',
        'synopsis': 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
        'genres': ['Drama', 'Thriller'],
        'director': 'Bong Joon-ho',
        'cast': ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
        'year': 2019,
        'country': 'South Korea',
        'rating': 16,
    },
    {
        'id': 11,
        'name': 'The Shawshank Redemption',
        'synopsis': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        'genres': ['Drama'],
        'director': 'Frank Darabont',
        'cast': ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
        'year': 1994,
        'country': 'USA',
        'rating': 16,
    },
    {
        'id': 12,
        'name': 'Spirited Away',
        'synopsis': 'During her family’s move to the suburbs, a 10-year-old girl wanders into a world ruled by gods, spirits, and a witch, where humans are turned into beasts.',
        'genres': ['Animation', 'Fantasy', 'Adventure'],
        'director': 'Hayao Miyazaki',
        'cast': ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
        'year': 2001,
        'country': 'Japan',
        'rating': 10,
    },
    {
        'id': 13,
        'name': 'The Godfather',
        'synopsis': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        'genres': ['Crime', 'Drama'],
        'director': 'Francis Ford Coppola',
        'cast': ['Marlon Brando', 'Al Pacino', 'James Caan'],
        'year': 1972,
        'country': 'USA',
        'rating': 18,
    },
    {
        'id': 14,
        'name': 'Interstellar',
        'synopsis': 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.',
        'genres': ['Adventure', 'Drama', 'Sci-Fi'],
        'director': 'Christopher Nolan',
        'cast': ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
        'year': 2014,
        'country': 'USA',
        'rating': 12,
    },
    {
        'id': 15,
        'name': 'The Social Network',
        'synopsis': 'Harvard student Mark Zuckerberg creates the social networking site that would become Facebook, but is later sued by two brothers who claimed he stole their idea.',
        'genres': ['Biography', 'Drama'],
        'director': 'David Fincher',
        'cast': ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
        'year': 2010,
        'country': 'USA',
        'rating': 14,
},
{    
        
        'id': 16,
        'name': 'Norbit',
        'synopsis': 'Um homem tímido é forçado a se casar com uma mulher dominadora, até reencontrar o amor de sua infância.',
        'genres': ['Comedy', 'Romance'],
        'director': 'Brian Robbins',
        'cast': ['Eddie Murphy', 'Thandiwe Newton', 'Cuba Gooding Jr.'],
        'year': 2007,
        'country': 'USA',
        'rating': 12
        

},
{
        'id': 17,
        'name': 'Pulp Fiction',
        'synopsis': 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
        'genres': ['Crime', 'Drama'],
        'director': 'Quentin Tarantino',
        'cast': ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
        'year': 1994,
        'country': 'USA',
        'rating': 18,
},
{
        'id': 18,
        'name': 'Forrest Gump',
        'synopsis': 'The life journey of Forrest Gump, a slow-witted but kind-hearted man from Alabama, as he inadvertently influences several historical events.',
        'genres': ['Drama', 'Romance'],
        'director': 'Robert Zemeckis',
        'cast': ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        'year': 1994,
        'country': 'USA',
        'rating': 12,
},
{
        'id': 19,
        'name': 'The Matrix',
        'synopsis': 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.',
        'genres': ['Action', 'Sci-Fi'],
        'director': 'Lana Wachowski, Lilly Wachowski',
        'cast': ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
        'year': 1999,
        'country': 'USA',
        'rating': 14,
},
{
        'id': 20,
        'name': 'Fight Club',
        'synopsis': 'An insomniac office worker and a soap salesman form an underground fight club that evolves into something much more.',
        'genres': ['Drama'],
        'director': 'David Fincher',
        'cast': ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
        'year': 1999,
        'country': 'USA',
        'rating': 18,
},
{    
        'id': 21,
        'name': 'Avengers: Endgame',
        'synopsis': 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos\' actions and restore balance to the universe.',
        'genres': ['Action', 'Adventure', 'Sci-Fi'],
        'director': 'Anthony Russo, Joe Russo',
        'cast': ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
        'year': 2019,
        'country': 'USA',
        'rating': 12


},
{
        'id': 22,
        'name': 'Coco',
        'synopsis': 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
        'genres': ['Animation', 'Adventure', 'Family'],
        'director': 'Lee Unkrich',
        'cast': ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt'],
        'year': 2017,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 23,
        'name': 'Whiplash',
        'synopsis': 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams are mentored by an abusive instructor.',
        'genres': ['Drama', 'Music'],
        'director': 'Damien Chazelle',
        'cast': ['Miles Teller', 'J.K. Simmons', 'Paul Reiser'],
        'year': 2014,
        'country': 'USA',
        'rating': 16,
},
{
        'id': 24,
        'name': 'The Lion King',
        'synopsis': 'A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and bravery.',
        'genres': ['Animation', 'Adventure', 'Drama'],
        'director': 'Roger Allers, Rob Minkoff',
        'cast': ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
        'year': 1994,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 25,
        'name': 'Shrek',
        'synopsis': 'An ogre’s peaceful life is disrupted when fairytale creatures are exiled to his swamp by an evil lord.',
        'genres': ['Animation', 'Adventure', 'Comedy'],
        'director': 'Andrew Adamson, Vicky Jenson',
        'cast': ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz'],
        'year': 2001,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 26,
        'name': 'Django Unchained',
        'synopsis': 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner.',
        'genres': ['Drama', 'Western'],
        'director': 'Quentin Tarantino',
        'cast': ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio'],
        'year': 2012,
        'country': 'USA',
        'rating': 18,
},
{
        'id': 27,
        'name': 'Gladiator',
        'synopsis': 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.',
        'genres': ['Action', 'Adventure', 'Drama'],
        'director': 'Ridley Scott',
        'cast': ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
        'year': 2000,
        'country': 'USA',
        'rating': 16,
},
{
        'id': 28,
        'name': 'WALL·E',
        'synopsis': 'In a distant future, a small waste-collecting robot inadvertently embarks on a space journey that will decide the fate of mankind.',
        'genres': ['Animation', 'Adventure', 'Family'],
        'director': 'Andrew Stanton',
        'cast': ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin'],
        'year': 2008,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 29,
        'name': 'La La Land',
        'synopsis': 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.',
        'genres': ['Comedy', 'Drama', 'Music'],
        'director': 'Damien Chazelle',
        'cast': ['Ryan Gosling', 'Emma Stone', 'John Legend'],
        'year': 2016,
        'country': 'USA',
        'rating': 12,
},
{
        'id': 30,
        'name': 'The Revenant',
        'synopsis': 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead.',
        'genres': ['Action', 'Adventure', 'Drama'],
        'director': 'Alejandro G. Iñárritu',
        'cast': ['Leonardo DiCaprio', 'Tom Hardy', 'Domhnall Gleeson'],
        'year': 2015,
        'country': 'USA',
        'rating': 16,
},
{
        'id': 31,
        'name': 'The Truman Show',
        'synopsis': 'An insurance salesman discovers his entire life is actually a reality TV show.',
        'genres': ['Comedy', 'Drama'],
        'director': 'Peter Weir',
        'cast': ['Jim Carrey', 'Ed Harris', 'Laura Linney'],
        'year': 1998,
        'country': 'USA',
        'rating': 12,
},
{
        'id': 32,
        'name': 'The Silence of the Lambs',
        'synopsis': 'A young FBI cadet must confide in an incarcerated and manipulative killer to catch another serial killer.',
        'genres': ['Crime', 'Drama', 'Thriller'],
        'director': 'Jonathan Demme',
        'cast': ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney'],
        'year': 1991,
        'country': 'USA',
        'rating': 18,
},
{
        'id': 33,
        'name': 'Titanic',
        'synopsis': 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
        'genres': ['Drama', 'Romance'],
        'director': 'James Cameron',
        'cast': ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
        'year': 1997,
        'country': 'USA',
        'rating': 12,
},
{
        'id': 34,
        'name': 'The Prestige',
        'synopsis': 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.',
        'genres': ['Drama', 'Mystery', 'Sci-Fi'],
        'director': 'Christopher Nolan',
        'cast': ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson'],
        'year': 2006,
        'country': 'USA',
        'rating': 14,
},
{
        'id': 35,
        'name': 'Black Panther',
        'synopsis': 'T’Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.',
        'genres': ['Action', 'Adventure', 'Sci-Fi'],
        'director': 'Ryan Coogler',
        'cast': ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o'],
        'year': 2018,
        'country': 'USA',
        'rating': 12,
},
{
        'id': 36,
        'name': 'Finding Nemo',
        'synopsis': 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.',
        'genres': ['Animation', 'Adventure', 'Comedy'],
        'director': 'Andrew Stanton',
        'cast': ['Albert Brooks', 'Ellen DeGeneres', 'Alexander Gould'],
        'year': 2003,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 37,
        'name': 'Inside Out',
        'synopsis': 'After young Riley is uprooted from her Midwest life, her emotions—Joy, Fear, Anger, Disgust and Sadness—conflict on how to best navigate a new city.',
        'genres': ['Animation', 'Adventure', 'Comedy'],
        'director': 'Pete Docter',
        'cast': ['Amy Poehler', 'Bill Hader', 'Lewis Black'],
        'year': 2015,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 38,
        'name': 'A Beautiful Mind',
        'synopsis': 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.',
        'genres': ['Biography', 'Drama'],
        'director': 'Ron Howard',
        'cast': ['Russell Crowe', 'Ed Harris', 'Jennifer Connelly'],
        'year': 2001,
        'country': 'USA',
        'rating': 14,
},
{
        'id': 39,
        'name': 'The Imitation Game',
        'synopsis': 'During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.',
        'genres': ['Biography', 'Drama', 'Thriller'],
        'director': 'Morten Tyldum',
        'cast': ['Benedict Cumberbatch', 'Keira Knightley', 'Matthew Goode'],
        'year': 2014,
        'country': 'UK',
        'rating': 12,
},
{
        'id': 40,
        'name': 'The Pursuit of Happyness',
        'synopsis': 'A struggling salesman takes custody of his son as he’s poised to begin a life-changing professional endeavor.',
        'genres': ['Biography', 'Drama'],
        'director': 'Gabriele Muccino',
        'cast': ['Will Smith', 'Thandiwe Newton', 'Jaden Smith'],
        'year': 2006,
        'country': 'USA',
        'rating': 12,
},
{
        'id': 41,
        'name': 'Up',
        'synopsis': 'An old man ties thousands of balloons to his house and flies to South America, accompanied by an unexpected young stowaway.',
        'genres': ['Animation', 'Adventure', 'Comedy'],
        'director': 'Pete Docter, Bob Peterson',
        'cast': ['Edward Asner', 'Jordan Nagai', 'John Ratzenberger'],
        'year': 2009,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 42,
        'name': 'The Incredibles',
        'synopsis': 'A family of undercover superheroes are forced into action to save the world.',
        'genres': ['Animation', 'Action', 'Adventure'],
        'director': 'Brad Bird',
        'cast': ['Craig T. Nelson', 'Holly Hunter', 'Samuel L. Jackson'],
        'year': 2004,
        'country': 'USA',
        'rating': 10,
},
{
        'id': 43,
        'name': 'Slumdog Millionaire',
        'synopsis': 'A Mumbai teen reflects on his life after being accused of cheating on the Indian version of "Who Wants to Be a Millionaire?"',
        'genres': ['Drama', 'Romance'],
        'director': 'Danny Boyle',
        'cast': ['Dev Patel', 'Freida Pinto', 'Anil Kapoor'],
        'year': 2008,
        'country': 'UK',
        'rating': 14,
},
{
        'id': 44,
        'name': 'The Grand Budapest Hotel',
        'synopsis': 'The adventures of a legendary concierge and his protégé at a famous European hotel between the wars.',
        'genres': ['Adventure', 'Comedy', 'Crime'],
        'director': 'Wes Anderson',
        'cast': ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
        'year': 2014,
        'country': 'USA',
        'rating': 14,
},
{
        'id': 45,
        'name': 'Her',
        'synopsis': 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.',
        'genres': ['Drama', 'Romance', 'Sci-Fi'],
        'director': 'Spike Jonze',
        'cast': ['Joaquin Phoenix', 'Scarlett Johansson', 'Amy Adams'],
        'year': 2013,
        'country': 'USA',
        'rating': 16,
},
{
        'id': 46,
        'name': 'Joker',
        'synopsis': 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded by society and turns to a life of crime.',
        'genres': ['Crime', 'Drama', 'Thriller'],
        'director': 'Todd Phillips',
        'cast': ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
        'year': 2019,
        'country': 'USA',
        'rating': 18,
},
{         
        'id': 47,
        'name': 'White Chicks',
        'synopsis': 'Two FBI agents go undercover as white socialite women to solve a kidnapping case involving spoiled heiresses.',
        'genres': ['Comedy', 'Crime'],
        'director': 'Keenen Ivory Wayans',
        'cast': ['Shawn Wayans', 'Marlon Wayans', 'Busy Philipps'],
        'year': 2004,
        'country': 'USA',
        'rating': 12,


},
{
        'id': 48,
        'name': 'Braveheart',
        'synopsis': 'Scottish warrior William Wallace leads his countrymen in a rebellion against English rule.',
        'genres': ['Biography', 'Drama', 'History'],
        'director': 'Mel Gibson',
        'cast': ['Mel Gibson', 'Sophie Marceau', 'Patrick McGoohan'],
        'year': 1995,
        'country': 'USA',
        'rating': 16,
},
{   
        'id': 49,
        'name': 'The Fast and the Furious',
        'synopsis': 'An undercover cop infiltrates the world of street racing to investigate a string of hijackings, but finds himself drawn to the lifestyle and the people.',
        'genres': ['Action', 'Crime', 'Thriller'],
        'director': 'Rob Cohen',
        'cast': ['Paul Walker', 'Vin Diesel', 'Michelle Rodriguez'],
        'year': 2001,
        'country': 'USA',
        'rating': 14,


},
{
        'id': 50,
        'name': 'The Hunger Games',
        'synopsis': 'Katniss Everdeen volunteers to take her sister’s place in a televised fight to the death in a dystopian future.',
        'genres': ['Action', 'Adventure', 'Sci-Fi'],
        'director': 'Gary Ross',
        'cast': ['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth'],
        'year': 2012,
        'country': 'USA',
        'rating': 14,
},


 
]

@app.route('/movies', methods=['GET'])  # Enables movie search

def get_movies():
    return jsonify(movies)  # Returns movie list in JSON format


@app.route('/movies/<int:id>', methods=['GET'])  # Enables movie search by ID

def get_movie_by_id(id):
    for movie in movies:
        if movie.get('id') == id:
            return jsonify(movie)
    return jsonify({"error": "Movie not found"}), 404


@app.route('/movies/search', methods=['GET'])  # Enables movie search by name

def search_by_name():
    name = request.args.get('name', '')  # Gets the 'name' parameter from the query URL

    if name:
        result = [movie for movie in movies if name.lower() in movie['name'].lower()]
        if result:
            return jsonify(result)
        else:
            return jsonify({"error": "No movies found with that name"}), 404
    else:
        return jsonify({"error": "You must provide a name to search"}), 404
    



if __name__ == '__main__':
    app.run(port=5000, host='localhost', debug=True)
